### ISSUE TITLE
cannot open fontfile

### ISSUE THREAD

**Issue by llbook** [stetre/moonfreetype#1]
"face = ft.new_face(lib, fontfile)" in the examples results in:
stdin:1: unknown file format
stack traceback:
        [C]: in function 'moonfreetype.new_face'
        stdin:1: in main chunk
        [C]: in ?

The version-example works alright, however:
$ lua version.lua
MoonFreeType 0.2
FreeType 2.9.0

I am running windows8.1 and have followed the installation instructions.

**Comment by stetre** [comment]
Hi, which example gave you this error? And which font file did you use?
It seems that you used a font file that is either corrupted or of a not supported format.

**Comment by llbook** [comment]
Yes, the arial.ttf file that got installed in the example library could not be opened by windows8.1

Once I copied arial.ttf from the windows font directory into the example directory the function
'face = ft.new_face(lib, "arial.ttf")'
worked alright.

However, that font file has no glyph names, so
face:has_glyph_names( )
returns false, and the listglyphs.lua example fails.

Thanks - great library!
