### ISSUE TITLE
Ubuntu 22.04: ft2build.h is not found with libfreetype-dev and libfreetype6-dev installed

### ISSUE THREAD

**Issue by jordan4ibanez** [stetre/moonfreetype#2]
```
moonfreetype.h:38:10: fatal error: ft2build.h: No such file or directory
   38 | #include <ft2build.h>
      |          ^~~~~~~~~~~~

```
This is the error I am getting. I've triple checked everything and it is simply not finding anything related to ft2build.h.

**Comment by stetre** [comment]
Please run these two commands and report their output:

`$ locate ft2build.h`

`$ freetype-config --cflags`
